---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c4a0b88
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
  -   repo: https://github.com/doublify/pre-commit-rust
      rev: master
      hooks:
      -   id: fmt
      -   id: cargo-check
